### ISSUE TITLE
Create post page doesn't have any validation message when i don't fill in the required fields

### ISSUE THREAD

**Issue by iMagesh** [MilesUpHQ/reddit-clone-rails#100]

**Comment by ksowndar** [comment]
In create post the validation message is added for required fields @iMagesh 
![image](https://user-images.githubusercontent.com/84360457/210938437-ada6f9b2-27ff-4ebf-a446-d1aaa0d489e7.png)

**Comment by Venirails** [comment]
Error message should be "body can't be blank".  Here Body ,Title Displayed twice.Remove the repeated "Body" "Title" words.

**Comment by Aboorva1** [comment]
Changes done and given pull request
