### ISSUE TITLE
Create post page should not be available to users when he has not joined/owns any community

### ISSUE THREAD

**Issue by iMagesh** [MilesUpHQ/reddit-clone-rails#102]
It is pointless to let a user access a create post and not be able to do anything there

**Comment by ksowndar** [comment]
It is now visible only to those who have joined the community, Please check with following PR and image is attached
https://github.com/MilesUpHQ/reddit-clone-rails/pull/140
![image](https://user-images.githubusercontent.com/84360457/210941819-b069b0a0-c04e-408f-bb54-7e01ec1e0191.png)
