### ISSUE TITLE
Home page - there are a lot of empty spaces after the post list ends

### ISSUE THREAD

**Issue by iMagesh** [MilesUpHQ/reddit-clone-rails#105]
<img width="1352" alt="Screenshot 2023-01-04 at 1 44 14 PM" src="https://user-images.githubusercontent.com/84182/210511841-a144b08d-2b2d-40ac-a1be-a03ce8892ded.png">

**Comment by ksowndar** [comment]
It is solved in this pull request, Please check it
https://github.com/MilesUpHQ/reddit-clone-rails/pull/125
![image](https://user-images.githubusercontent.com/84360457/210725961-695ba8e8-9650-40e6-93d9-caf53d5bb215.png)
