### ISSUE TITLE
Infinity scroll shows an extra link in between posts which is not required

### ISSUE THREAD

**Issue by iMagesh** [MilesUpHQ/reddit-clone-rails#106]
<img width="783" alt="Screenshot 2023-01-04 at 1 47 39 PM" src="https://user-images.githubusercontent.com/84182/210513008-fe052942-c8b1-423e-b206-f81b529a8936.png">

**Comment by ksowndar** [comment]
It is solved in pull request, Please check it
https://github.com/MilesUpHQ/reddit-clone-rails/pull/125
![image](https://user-images.githubusercontent.com/84360457/210725730-8fc64873-fe16-4154-b772-c0ee9e822a72.png)
