### ISSUE TITLE
3 Bugs in post drafts page

### ISSUE THREAD

**Issue by 78-karthi** [MilesUpHQ/reddit-clone-rails#117]
1. The name of community is not getting displayed when we open the draft post. (image 1)
![image 1](https://user-images.githubusercontent.com/121854722/210547866-6008223a-ad56-48d9-a3da-ccd56371d8f4.jpg)
2. when we click publish after editing the draft, it asks us to select the community once again. (image 2)
![image 2](https://user-images.githubusercontent.com/121854722/210548234-7c0e16b8-619a-4008-9622-196dffdbfabc.jpg)

3. while we are inside a draft post, we are unable to view other drafts when we click on the drafts button (image 3)
![image 3](https://user-images.githubusercontent.com/121854722/210548249-a7ec38b8-db4e-4819-95f2-c75c45f9fae5.jpg)

**Comment by mithun30052001** [comment]
These three errors are fixed in #111  and merged into master
