### ISSUE TITLE
If the user hasn't created any post, the posts tab in user profile should show the user has not posted anything yet.

### ISSUE THREAD

**Issue by 78-karthi** [MilesUpHQ/reddit-clone-rails#143]

**Comment by ksowndar** [comment]
The empty message is added, Please check it, the screenshot is attached below
https://github.com/MilesUpHQ/reddit-clone-rails/pull/157
![image](https://user-images.githubusercontent.com/84360457/211091463-74ef9211-6bba-4e57-85e6-d3aba0479a03.png)
