### ISSUE TITLE
Design issues on post show page - comments

### ISSUE THREAD

**Issue by iMagesh** [MilesUpHQ/reddit-clone-rails#163]
Check the alignment, spacing, and font size for the marked items and make sure they are the same as given in Reddit
These subtle things can go a long way in improving the quality of the UI

<img width="783" alt="Screenshot 2023-01-09 at 5 11 43 PM" src="https://user-images.githubusercontent.com/84182/211300461-f84da3ca-2c0b-400c-8368-21b37e5d6110.png">

**Comment by ksowndar** [comment]
The dessign issue is fixed @iMagesh, Please check with following PR
https://github.com/MilesUpHQ/reddit-clone-rails/pull/171
![image](https://user-images.githubusercontent.com/84360457/211322625-5bf4b2bf-58e3-43d0-b43a-259824a11309.png)

**Comment by christophersongalvez20** [comment]
Hi,
Christopson here,
I'm experiencing the same problem; when I design my [site](https://thecourtdirect.com/woodbridge-municipal-court/).
I would appreciate it if you could let me know if the answer is correct.
I appreciate your help.

**Comment by tusharravindran** [comment]
Design is Fixed when tested  when pulled form master on 20-01-2023
