### ISSUE TITLE
The community category created on the admin side is not reflecting on the user side.

### ISSUE THREAD

**Issue by 78-karthi** [MilesUpHQ/reddit-clone-rails#166]

**Comment by ksowndar** [comment]
The category created on admin side is reflecting in user side, for that we need to restart the server, then only the data created by admin reflect in user side.  
![image](https://user-images.githubusercontent.com/84360457/211463377-dd092659-6a64-445e-ab4a-86d114cf5fa9.png)
![image](https://user-images.githubusercontent.com/84360457/211463418-1b47ca57-9573-4032-a5f4-a8d01692e530.png)
