### ISSUE TITLE
When we create a new community from the admin side, the category of community is not displayed. Instead, the category is displayed.

### ISSUE THREAD

**Issue by 78-karthi** [MilesUpHQ/reddit-clone-rails#168]
![category number](https://user-images.githubusercontent.com/121854722/211315469-c1c73f2f-5567-494e-9d78-ae2a859907c8.jpg)

**Comment by ksowndar** [comment]
Now it is corrected, the name of category will visible, Please check with following PR
https://github.com/MilesUpHQ/reddit-clone-rails/pull/174
![image](https://user-images.githubusercontent.com/84360457/211465185-a9965025-93d6-48b9-80e2-bae1b6fd7cf3.png)
![image](https://user-images.githubusercontent.com/84360457/211465236-d74c46fb-cd87-4051-9346-4e6f3548e28d.png)
