### ISSUE TITLE
At the admin side, community page the category disappears when we click on edit community.

### ISSUE THREAD

**Issue by 78-karthi** [MilesUpHQ/reddit-clone-rails#170]

**Comment by ksowndar** [comment]
The edit form is now corrected, now the category will not disappears when we trying to edit the community in admin side.
Please check with following PR, please verify the images attached.
https://github.com/MilesUpHQ/reddit-clone-rails/pull/183
![image](https://user-images.githubusercontent.com/84360457/211792105-2d4dba85-3ea9-4333-b8c3-f8bdc5e4a184.png)
