### ISSUE TITLE
Report post

### ISSUE THREAD

**Issue by Aboorva1** [MilesUpHQ/reddit-clone-rails#185]
![Screenshot (60)](https://user-images.githubusercontent.com/113507326/211804629-29a3d9b8-7c00-48dc-9f39-81c6e406d1fb.png)
![Screenshot (61)](https://user-images.githubusercontent.com/113507326/211804672-d88028aa-c184-4df1-86a8-b4a07a7b06e5.png)
In admin side, report category and reason remains same even if different report submitted

**Comment by ksowndar** [comment]
Now it is corrected, the report category and reason is correctly visible now, Please check with following PR is attached, and image is attached for verification, please check with it @Aboorva1 
https://github.com/MilesUpHQ/reddit-clone-rails/pull/187
![image](https://user-images.githubusercontent.com/84360457/211807109-b5ff271a-dc94-47c1-a0b3-cb5390f630c6.png)
