### ISSUE TITLE
routes.rb - Group as members and add namespace

### ISSUE THREAD

**Issue by vasanthakumar-a** [MilesUpHQ/reddit-clone-rails#198]
In routes.rb file ,

1. Group all the resources path and add members in it
2. Order them in an alphabetical order
3. Use namespace instead of path: 'r' , path: 'p'

**Comment by vasanthakumar-a** [comment]
use rubocop extension for refactoring the code

**Comment by ksowndar** [comment]
Instead of path we can't namespace @vasanthakumar-a , I tried it showing error
