### ISSUE TITLE
Association - use association effectively in posts_controller.rb

### ISSUE THREAD

**Issue by vasanthakumar-a** [MilesUpHQ/reddit-clone-rails#204]
1. instead of  `@post = Post.find(params[:id])` , use `@post = @community.posts.find(params[:id])` in all occurrence
2. Don't pass post_id, community_id in controller permit params

**Comment by vasanthakumar-a** [comment]
use rubocop extension for refactoring the code

**Comment by Aboorva1** [comment]
Completed and PR is merged to master
