### ISSUE TITLE
search field duplicated while using the website for sometime

### ISSUE THREAD

**Issue by iMagesh** [MilesUpHQ/reddit-clone-rails#213]
I was just testing all the pages by visiting the links, added a few posts and comments. Later i see this on the home page

<img width="848" alt="Screenshot 2023-01-18 at 7 49 15 PM" src="https://user-images.githubusercontent.com/84182/213195510-cb7316f1-ed24-431c-8923-02a85e227c38.png">

**Comment by mithun30052001** [comment]
it seems the field appeared multiple times due to cache stored so this is cleared by using no cache method and a seperate form for the autocomplete field

**Comment by tusharravindran** [comment]
Issue Resolved after Testing on 20-01-2023 .Issue Resolved
