### ISSUE TITLE
Content warning features are missing

### ISSUE THREAD

**Issue by SrinandhiniM** [MilesUpHQ/reddit-clone-rails#216]
Spoiler contents,nsfw contents and oc tags contents features are now missing in Master.

**Comment by iMagesh** [comment]
What happened? check all the commits and find out where/when it happened. @SrinandhiniM @tusharravindran @vasanthakumar-a @ksowndar @Aboorva1 @mithun30052001

**Comment by SrinandhiniM** [comment]
It is because we rendered form inside another form, so it is missing locals @iMagesh , so it is not submitting , I am resolving it.

**Comment by SrinandhiniM** [comment]
Solved this issue and it was merged in Master
