### ISSUE TITLE
Signup issue - SMTP mail triggers 

### ISSUE THREAD

**Issue by Venirails** [MilesUpHQ/reddit-clone-rails#30]
When I create a new user, I am getting this error while triggering outbound email for signup notification.

I added .env file as well

<img width="1280" alt="Screenshot 2022-12-28 at 11 48 17 AM" src="https://user-images.githubusercontent.com/7172445/209767493-180478bd-e4ab-4583-8545-b31dabd1e723.png">

if I am disabling  .env file, this error occurs 

<img width="1052" alt="Screenshot 2022-12-28 at 11 52 37 AM" src="https://user-images.githubusercontent.com/7172445/209767714-88b070ae-5a8f-4c9f-bec1-e89b32702875.png">

This problem is due to Mailgun / SMTP setup. 

Suggestion:You can check with Magesh to change this MAILGUN to SENDGRID

**Comment by tusharravindran** [comment]
![image](https://user-images.githubusercontent.com/57782379/209769399-322c2554-b3f3-4e2b-913b-5bbea58168c3.png)

A mail will be sent to 
[krishnaveni@sedintechnologies.com]

Confirm it and Try Signup 

It will send Confirmation mail to  
[krishnaveni@sedintechnologies.com] with auth token 

Now Login with the Link given in mail (Auth Token -> Cookies)

**Comment by tusharravindran** [comment]
I tried sengrid it asks for credit card details for account , Mailgun gives free account for trail accounts with 5 Authorized Recipients
![image](https://user-images.githubusercontent.com/57782379/209769891-7c280ba0-3560-4728-b4f9-6c6c410a549b.png)

**Comment by iMagesh** [comment]
@tusharravindran can you add exception handling for this? even when there is no email permission it should not crash, instead, it can skip the email and continue to the application right?

**Comment by tusharravindran** [comment]
Resolved by exceptio handling
