### ISSUE TITLE
Alignment issues

### ISSUE THREAD

**Issue by Venirails** [MilesUpHQ/reddit-clone-rails#34]
Please check the pages

singup
login
create post

All the pages are loading in left alignment.

<img width="1267" alt="Screenshot 2022-12-28 at 3 35 26 PM" src="https://user-images.githubusercontent.com/7172445/209795344-626fdef6-605a-41c4-8006-5522952dc123.png">

Are we missing something ?

**Comment by SrinandhiniM** [comment]
Alignmnet issues are corrected now and PR raised.

**Comment by vasanthakumar-a** [comment]
Issue resolved and merged with master branch
