### ISSUE TITLE
Save/ Unsave

### ISSUE THREAD

**Issue by Venirails** [MilesUpHQ/reddit-clone-rails#36]
When I click on save / unsave only link is getting updated

It is not showing any notification to the user. Also if I scroll down and save a post at the bottom , it is taking me to the top of the page without any message.

please check

<img width="1166" alt="Screenshot 2022-12-28 at 3 56 58 PM" src="https://user-images.githubusercontent.com/7172445/209797990-48bc02dc-841f-4027-82b8-eeb43e8b3a5b.png">

**Comment by vasanthakumar-a** [comment]
This issue has been resolved and raised a pull request.

**Comment by tusharravindran** [comment]
This issue has been resolved and Merged

**Comment by Venirails** [comment]
@tusharravindran This issue is working after login. If I click on the save button without login, it should say something to login or it should be disabled. Now its not doing anything.please check
