### ISSUE TITLE
Save changes button not working

### ISSUE THREAD

**Issue by Aboorva1** [MilesUpHQ/reddit-clone-rails#50]
![Screenshot (55)](https://user-images.githubusercontent.com/113507326/210044973-4d2492b5-ef28-4a16-b406-c2296b8fad64.png)
Nothing happens when save changes button is clicked. What is the actual usage of the button ?

**Comment by mithun30052001** [comment]
Save changes button redirection is done in #bug/Zero_drafts_pop-up page
