### ISSUE TITLE
Drafts in new community page

### ISSUE THREAD

**Issue by Aboorva1** [MilesUpHQ/reddit-clone-rails#51]
Community does not have save as draft option. But there is a "Drafts" button in new community page
![Screenshot (56)](https://user-images.githubusercontent.com/113507326/210045409-c7556655-7f50-4c72-99a0-e84419b480df.png)

![Screenshot (54)](https://user-images.githubusercontent.com/113507326/210045426-59c62df2-9286-435e-bab3-de2ba650f9e6.png)

**Comment by mithun30052001** [comment]
Drafts in the new community page removed

**Comment by mithun30052001** [comment]
And the pull request is given for the same in #bug/Zero_drafts_pop-up
