### ISSUE TITLE
Community page - join button should not be seen next to all the posts

### ISSUE THREAD

**Issue by iMagesh** [MilesUpHQ/reddit-clone-rails#77]
<img width="783" alt="Screenshot 2023-01-03 at 2 05 11 PM" src="https://user-images.githubusercontent.com/84182/210323825-ac16bed8-dc31-4f06-bb66-58dbc95dc646.png">

**Comment by ksowndar** [comment]
It is removed, please check it in the following PR
https://github.com/MilesUpHQ/reddit-clone-rails/pull/79

![image](https://user-images.githubusercontent.com/84360457/210340579-b1694eed-2bc5-407f-b567-cd0898c74003.png)
