### ISSUE TITLE
At the settings page: 1. once the user makes the changes and clicks edit, the page reloads and the edit button changes to sign up button. 2. The 'didn't receive confirmation instructions?' link is not necessary for this page. 

### ISSUE THREAD

**Issue by 78-karthi** [MilesUpHQ/reddit-clone-rails#78]
![user settings](https://user-images.githubusercontent.com/121854722/210324058-9d8cec92-4943-455e-bb00-57295645c729.jpg)

**Comment by 78-karthi** [comment]
The edit button is fixed. But, the didn't receive confirmation instructions is not removed

**Comment by Venirails** [comment]
If edit the details and leave without giving the password, the design is getting break. (* field is coming in next line)
<img width="581" alt="Screenshot 2023-01-09 at 4 38 38 PM" src="https://user-images.githubusercontent.com/7172445/211295131-e12a41b6-4010-443e-b48b-7dcb3697b42c.png">

**Comment by Venirails** [comment]
if the error message is occurring, selected file becomes "No file choosen"

**Comment by vasanthakumar-a** [comment]
This issue is already noticed in #116

**Comment by Venirails** [comment]
try this solution


https://medium.com/@TETRA2000/active-storage-how-to-retain-uploaded-files-on-form-resubmission-91b57be78d53
